import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        paper: 'var(--paper)',
        'paper-raised': 'var(--paper-raised)',
        'paper-deep': 'var(--paper-deep)',
        glass: 'var(--glass)',
        'nav-bg': 'var(--nav-bg)',
        ink: 'var(--ink)',
        'ink-60': 'var(--ink-60)',
        'ink-30': 'var(--ink-30)',
        line: 'var(--line)',
        'glass-line': 'var(--glass-line)',
        'grid-ink': 'var(--grid-ink)',
        blueprint: 'var(--blueprint)',
        'blueprint-light': 'var(--blueprint-light)',
        'blueprint-strong': 'var(--blueprint-strong)',
        up: 'var(--up)',
        down: 'var(--down)',
      },
      fontFamily: {
        serif: 'var(--serif)',
        sans: 'var(--sans)',
        mono: 'var(--mono)',
      },
      fontSize: {
        '2xs': 'var(--text-2xs)',
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        md: 'var(--text-md)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
        '6xl': 'var(--text-6xl)',
        '7xl': 'var(--text-7xl)',
        heading: 'var(--text-heading)',
        hero: 'var(--text-hero)',
        'hero-sm': 'var(--text-hero-sm)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        pill: 'var(--radius-pill)',
        circle: 'var(--radius-circle)',
      },
      boxShadow: {
        1: 'var(--shadow-1)',
        2: 'var(--shadow-2)',
      },
      transitionDuration: {
        fast: 'var(--motion-fast)',
        base: 'var(--motion-base)',
        slow: 'var(--motion-slow)',
        slower: 'var(--motion-slower)',
        slowest: 'var(--motion-slowest)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        'out-back': 'var(--ease-out-back)',
        out: 'var(--ease-out)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        12: 'var(--space-12)',
        'section-y': 'var(--section-y)',
        'section-y-tablet': 'var(--section-y-tablet)',
        'section-y-phone': 'var(--section-y-phone)',
      },
      maxWidth: {
        maxw: 'var(--maxw)',
      },
    },
  },
  plugins: [],
};

export default config;
